FULLSCREEN = true;
SCREEN_WIDTH = 1600;
SCREEN_HEIGHT = 900;

ROOM_WIDTH = 2000;
ROOM_HEIGHT = 900;

KEY_LEFT = "left";
KEY_RIGHT = "right";
KEY_JUMP = "a";
KEY_QUIT = "escape";

GAMEPAD_LEFT = "dpleft";
GAMEPAD_RIGHT = "dpright";
GAMEPAD_UP = "dpup";
GAMEPAD_DOWN = "dpdown";
GAMEPAD_A = "a";
GAMEPAD_B = "b";
GAMEPAD_X = "x";
GAMEPAD_Y = "y";
GAMEPAD_LEFT_STICK = "leftstick";
GAMEPAD_RIGHT_STICK = "rightstick";
GAMEPAD_LEFT_SHOULDER = "leftshoulder";
GAMEPAD_RIGHT_SHOULDER = "rightshoulder";
GAMEPAD_START = "start";
GAMEPAD_QUIT = "back";

GAMEPAD_DEADZONE = 0.75;

WALL_SIZE = 50;
BALL_SIZE = 20;
BALL_SPEED = 300;

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789";
LETTER_TIMER = 3;
